name: Picker Plugins
on:
  push:
    branches: [ develop ]
  create:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup repository env
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install deps
      run: npm install
    - name: Bundle packages
      run: npx gulp bundle
    - name: Release packages
      run: npx gulp publish
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
